# Generated by Django 3.0.6 on 2021-04-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210414_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
