# Generated by Django 3.0.6 on 2021-04-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_userproduct_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
